apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgresql.metadata.name }}
  namespace: {{ .Values.postgresql.namespace }}
  labels:
    app: {{ .Values.postgresql.metadata.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgresql.metadata.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgresql.metadata.name }}
    spec:
      volumes:
        - name: postgresql-data-pvc
          persistentVolumeClaim:
            claimName: postgresql-data-pvc
      containers:
      - name: {{ .Values.postgresql.metadata.name }}
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.secret.name }}
              key: {{ .Values.postgresql.secret.postgresqlpassword.key }}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.postgresql.secret.name }}
              key: {{ .Values.postgresql.secret.postgresqluser.key }}
        ports:
        - containerPort: 5432  
        volumeMounts:
         - name: postgresql-data-pvc
           mountPath: /var/lib/postgresql/data
        resources:
          limits:
            cpu: {{ .Values.postgresql.resources.limits.cpu }}
            memory: {{ .Values.postgresql.resources.limits.memory }}
          requests:
            cpu: {{ .Values.postgresql.resources.requests.cpu }}
            memory: {{ .Values.postgresql.resources.requests.memory }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "$(POSTGRES_USER)" -h 127.0.0.1 -p 5432
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds:   