apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.metadata.name }}-secret
  namespace:  {{ .Values.postgresql.namespace }}
  annotations:
   "helm.sh/hook": pre-install
data:
 {{ .Values.postgresql.secret.postgresqlpassword.key }} : {{ .Values.postgresql.secret.postgresqlpassword.value }}
 {{ .Values.postgresql.secret.postgresqluser.key }} : {{ .Values.postgresql.secret.postgresqluser.value }}
 {{ .Values.postgresql.secret.postgresqldb.key }} : {{ .Values.postgresql.secret.postgresqldb.value }}
 {{ .Values.postgresql.secret.postgresqlhost.key }} : {{ .Values.postgresql.secret.postgresqlhost.value }}
 