apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresql.metadata.name }}-service
  namespace: {{ .Values.postgresql.namespace }}
spec:
  type: {{ .Values.postgresql.service.type }}
  selector:
    app: {{ .Values.postgresql.metadata.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.targetPort }}