apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.metadata.name }}-secret
  namespace:  {{ .Values.redis.namespace }}
  annotations:
   "helm.sh/hook": pre-install
data:
 {{ .Values.redis.secret.key }} : {{ .Values.redis.secret.value }}