apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.metadata.name }}-service
  namespace: {{ .Values.redis.namespace }}
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: {{ .Values.redis.metadata.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      nodePort: {{ .Values.redis.service.nodePort }}