postgresql:
  enabled: true
  namespace: postgresql
  metadata:
   name: postgresql
  image:
    repository: postgres
    tag: "latest"
  volumes:  
     name: postgresql-data-pvc
     persistentVolumeClaim:
         claimName: postgresql-data-pvc
     configmap:
        name: postgresql.conf
        configMap:
           name: postgresql.conf
           items:
             key: postgresql.conf
             path: postgresql.conf
  service:
    type: NodePort
    port: 5432
    nodePort: 32432
  resources:
    limits:
     cpu: 400m
     memory: 2Gi   
    requests:
     cpu: 200m
     memory: 1Gi
  secret:
    create: true
    name: postgresql-secret
    postgresqlpassword:
      key: postgresql_password
      value: Y2hhbGxlbmdl
    postgresqluser:
      key: postgresql_user
      value: cG9zdGdyZXMK
    postgresqldb:  
      key: postgresql_db
      value: cG9zdGdyZXMK
    postgresqlhost:
      key: postgresql_host
      value: cG9zdGdyZXNxbC1zZXJ2aWNl


redis:
  enabled: true
  namespace: redis
  metadata:
   name: redis
  image:
    repository: redis
    tag: "6"
  volumes:  
     name: redis-data-pvc
     persistentVolumeClaim:
         claimName: redis-data-pvc
  service:
    type: NodePort
    port: 6379
    nodePort: 32379
  resources:
    limits:
     cpu: 400m
     memory: 2Gi   
    requests:
     cpu: 200m
     memory: 1Gi
  livenessProbe:
    httpGet:
      path: /ping
      port: 6379
  readinessProbe:
    httpGet:
      path: /ping
      port: 6379
  secret:
    create: true
    name: redis-secret
    key: redis-password
    value: Y2hhbGxlbmdl
    