postgresql:
  enabled: true
  namespace: postgresql
  metadata:
   name: postgresql
  image:
    repository: postgres
    tag: "latest"
  service:
    type: LoadBalancer
    port: 32432
    targetPort: 5432
  resources:
    limits:
     cpu: 400m
     memory: 2Gi   
    requests:
     cpu: 200m
     memory: 1Gi
  secret:
    create: true
    name: postgresql-secret
    postgresqlpassword:
      key: postgresql_password
      value: Y2hhbGxlbmdl
    postgresqluser:
      key: postgresql_user
      value: Y2hhbGxlbmdl
    postgresqldb:  
      key: postgresql_db
      value: Y2hhbGxlbmdl
    postgresqlhost:
      key: postgresql_host
      value: cG9zdGdyZXNxbC1zZXJ2aWNl


redis:
  enabled: true
  namespace: redis
  metadata:
   name: redis
  image:
    repository: redis
    tag: "6"
  service:
    type: LoadBalancer
    port: 32379
    targetPort: 6379
  resources:
    limits:
     cpu: 400m
     memory: 2Gi   
    requests:
     cpu: 200m
     memory: 1Gi
  secret:
    create: true
    name: redis-secret
    key: redis-password
    value: Y2hhbGxlbmdl
    